/* Copyright(c)  Ryuichiro Nakato <rnakato@iam.u-tokyo.ac.jp>
 * All rights reserved.
 */
#ifndef _DD_ENV_V_H_
#define _DD_ENV_V_H_

namespace {
  enum class LineType{CHIP, INPUT, RATIO, RATIO_GV, PVALUE_INTER, PVALUE_ENRICH};

  enum { OFFSET_X=190,
	 OFFSET_Y=50,
	 BOXHEIGHT_GENEBOX_EXON=140,
	 BOXHEIGHT_GENEBOX_NOEXON=60,
	 BOXHEIGHT_IDEOGRAM=8,
	 BOXHEIGHT_BEDANNOTATION=12,
	 BOXHEIGHT_GRAPH=80,
	 BOXHEIGHT_INTERACTION=45,
	 BOXHEIGHT_ChIADROP=300,
	 MERGIN_BETWEEN_EACHLAYER=30,
	 MERGIN_BETWEEN_DATA=10,
	 MERGIN_BETWEEN_GRAPH_DATA=15,
	 MERGIN_BETWEEN_READ_BED=15
  };
}

#endif /* _DD_ENV_V_H_ */
